development:
  adapter: mysql2
  host: localhost
  username: root
  password: 
  database: oja_development


test:
  adapter: mysql2
  host: localhost
  username: root
  password: 
  database: oja_test
